name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    format-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install --immutable

            - name: Check formatting
              run: yarn format:check

            - name: Build apps
              run: yarn nx run-many -t build -p project-one,project-two --configuration=development
